### ISSUE TITLE
conéctese a más de 1 servidor plex y muestre los datos de cada servidor

### ISSUE THREAD

**Issue by ClappTV** [JonnyWong16/plexpy#1664] opened 2022-02-21 17:44 UTC
### What is your feature request?

It would be nice if we could connect to more than 1 plex server at the same time, and see the statistics and other functions of each of them.

**Comment by samwiseg0** [comment] 2022-02-21 17:49
Duplicate of https://github.com/Tautulli/Tautulli/issues/113

**Closed as completed by samwiseg0** 2022-02-21 17:49 UTC
Labels: invalid:duplicate
