### ISSUE TITLE
Ability to see Downloads activity on Home / Dashboard

### ISSUE THREAD

**Issue by JStrongy** [JonnyWong16/plexpy#2009] opened 2023-02-27 10:54 UTC
### Is your feature request related to a problem?

No

### What is your feature request?

It would be useful for Tautulli to be able to monitor activity on the server, relating to Downloads.

Specifically, the addition of a Downloads progress card, onto the Tautulli dashboard, which provides this information.

The main use case would be on a mobile device, where you cannot easily open up Plex Web on a mobile browser.

### Are there any workarounds?

At present, you can see the below in Plex Web:

![image](https://user-images.githubusercontent.com/96826493/221544282-c9eef88e-e504-497b-aa60-15dd7b60ac15.png)

Frustratingly, if you actually click on Dashboard in Plex - you see nothing.

**Comment by samwiseg0** [comment] 2023-02-27 12:11
Duplicate of https://github.com/Tautulli/Tautulli/issues/1451

**Closed as completed** 2023-02-27 12:11 UTC
Labels: invalid:duplicate
