### ISSUE TITLE
Container shows unhealthy when using custom SSL port 443

### ISSUE THREAD

**Issue by EHRETic** [JonnyWong16/plexpy#2198] opened 2023-11-13 14:11 UTC
### Describe the Bug

Hello,

I'm using a macvlan container on the same network as my Plex server. I use my own certificate for all apps, including Tautulli.
(The particularity of macvlan is that it doesn't take the docker port mapping so you can only rely of the application's configuration or put the application behind a web proxy if you want to use standard port 443)
It means also Tautulli doesn't run behind a reverse proxy in my environment but as Tautulli offers the possibility to change the port, I'm using this possibility to use standard HTTPS port.

In this case, if I use port default 8181, no problem, no health check issue but as soon as I change the port to 443, despite everything looks good from Tautulli point of view, container shows unhealthy state (see screenshots)

Changing user to root (and changing config volume permissions accordingly) doesn't change the result.

Seems like port 8181 is hardcoded in health check.

Thanks for you help 😉

### Steps to Reproduce

1. Change config file http port to 443
2. Restart application
3. Container will remain in unhealthy state
4. Rollback to 8181 solves the issue

### Expected Behavior

Well, if the health script could take the http port mentioned in configuration file, that would be great 👌😉

### Screenshots

The error displayed in Portainer (but probably the same in proper docker):

![image](https://github.com/Tautulli/Tautulli/assets/28634810/96f3902e-a154-4681-abb6-b60e05b2eba7)

![image](https://github.com/Tautulli/Tautulli/assets/28634810/1e63005b-dfde-414f-9557-fb168a0cc34b)

### Tautulli Version

2.13.2

### Git Branch

master

### Git Commit Hash

c215afbf84baafb1a2020c2dc6e36944a6de1504

### Platform and Version

Docker 

### Python Version

3.9.18

### Browser and Version

Any

### Link to Logs

https://gist.github.com/EHRETic/c8ddb97a58adc6eea2694e6dd528dc3b

**Comment by JonnyWong16** [comment] 2023-11-13 16:07
Duplicate of #2121.

Override with your own healthcheck. 

https://github.com/Tautulli/Tautulli/blob/c215afbf84baafb1a2020c2dc6e36944a6de1504/Dockerfile#L28

https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck

**Closed as not planned** 2023-11-13 16:07 UTC
Labels: invalid:duplicate, wont-fix
